- name: Add helm repo
  command: helm repo add stable "{{ url_repo_helm }}"
  register: prometheus_add_repo

- name: Helm Update
  command: helm repo update
  register: prometheus_repo_update

- name: Helm Install Prometheus Operator
  command: helm install {{ deploy_prometheus }}
  register: prometheus_install