---
- hosts: k8s-master
  user: root
  gather_facts: no
  roles:
  - { role: deploy-monit-tools, tags: ["deploy_monit_tools_role"] }

- hosts: k8s-master
  user: root
  gather_facts: no
  roles:
  - { role: deploy-app-v1, tags: ["deploy_app_v1_role"] }