- name: Removendo Cluster Antigo
  command: kubeadm reset --force
  ignore_errors: yes

- name: Removendo Diretorios e Arquivos
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/.kube
    - /etc/cni/net.d/10-weave.conflist
    - /opt/giropops
    - /etc/docker/daemon.json
    - /usr/local/bin/helm
    - /opt/docker_install.sh
    - /tmp/get_helm.sh

- name: Unhold Packages
  command: "apt-mark unhold {{ item }}"
  with_items:
      - docker-ce
      - docker-ce-cli
      - kubelet
      - kubeadm
      - kubectl

- name: Remove os Pacotes Kubernetes e Docker
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
      - docker-ce
      - docker-ce-cli
