- name: Download Helm
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/get_helm.sh
    mode: "0755"
  register: download

- name: Instalando Helm
  command: /tmp/get_helm.sh
  when:
    - download.failed|bool == false
  register: install_helm
